/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2017-01-07 10:37:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\n");
      out.write("\n");
      out.write("<h2>Hotel California Bliss</h2>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<ul>\n");
      out.write("  <li><a class=\"active\" href=\"#home\">Home</a></li>\n");
      out.write("  <li><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("  <li><a href=\"roomtypes.jsp\">Room Types</a></li>\n");
      out.write("  <li><a href=\"booknow.jsp\">Book Now</a></li>\n");
      out.write("  <li><a href=\"signin.jsp\">Sign in</a></li>\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("<pre>\n");
      out.write("Visit New Delhi Area Attractions from Our Hotel\n");
      out.write("\n");
      out.write("The Country Inn & Suites By Carlson Sahibabad, Distt Ghaziabad (U.P.) provides comfortable hotel rooms less than one hour from Indira Gandhi International Airport (DEL) and within walking distance of the Vaishali Metro Station. Top sights, including Akshardham, Humayun's Tomb and Connaught Place, are all within a 30-minute taxi ride of the hotel. If youâre in the area for work, we are also less than seven minutes from Vasundhara and about 30 minutes from the East Delhi National Capital Region (NCR), Noida and Greater Noida.\n");
      out.write("\n");
      out.write("See what our guests are <a href='reviews.jsp'>saying about us.</a>\n");
      out.write("\n");
      out.write("Hotel Amenities & Services\n");
      out.write("Escape to the Country Inn & Suites where you can pamper yourself with a beauty treatment in the salon or a refreshing therapy at Revive spa. To help make your trip easier, we also offer a 3-D 52-seat private theatre and 24-hour travel services. Additional amenities include:\n");
      out.write("\n");
      out.write("Four Restaurants and One Tea Lounge\n");
      out.write("DVD Galleria 3-D (private theatre)\n");
      out.write("Travel Desk\n");
      out.write("Business Centre\n");
      out.write("Salon and Spa\n");
      out.write("Free High-Speed Internet\n");
      out.write("Outdoor Pool\n");
      out.write("Gym\n");
      out.write("Learn more about our hotelâs amenities and services.\n");
      out.write("\n");
      out.write("Our Rooms & Suites\n");
      out.write("Choose one of our 216 guest rooms and suites for comfortable accommodation with premium bedding and warm wood accents. After connecting to the free high-speed Internet access, you can easily respond to emails or plan the dayâs itinerary without leaving your room. Standard highlights include:\n");
      out.write("\n");
      out.write("Satellite TV\n");
      out.write("In-Room Dining, Available 24 Hours\n");
      out.write("Minibar and Refrigerator\n");
      out.write("Large Workspace and Comfortable Living Area\n");
      out.write("Coffee- and Tea-Maker\n");
      out.write("Two Bottles of Packaged Water per Day\n");
      out.write("If you want to upgrade your business trip or simply need additional space, book one of our Executive Suites and enjoy these extras:\n");
      out.write("\n");
      out.write("Living Room\n");
      out.write("Complimentary Buffet Breakfast\n");
      out.write("Bathrobe and Slippers\n");
      out.write("Free Use of Steam Room and Spa Tub\n");
      out.write("Where to Eat While Youâre Here \n");
      out.write("Enjoy delicious meals all day long when you dine at one of our on-site restaurants. Offering local and continental dishes, 64/6 is a multi-cuisine buffet restaurant with something for the whole family. You can order delicious vegetarian dishes at Kebab Junction, impress a client at Tatva or dine poolside at 3Bâs. CafÃ© J is open 24 hours a day, making it the perfect spot for a casual meal, pastries or coffee with colleagues.\n");
      out.write("\n");
      out.write("Things to Do near Ghaziabad\n");
      out.write("Our hotel is conveniently located near greater New Delhi attractions, including historic sites like the Red Fort (Lal Quila). Donât miss these favourites during your stay:\n");
      out.write("\n");
      out.write("Akshardham - Just 15 minutes away, Akshardham is a large Hindu temple constructed of nearly 6,000 tonnes of pink sandstone. The temple features a 60-acre garden, lifelike dioramas and an evening water show. Please note that phones, cameras and bags are not allowed in the complex.\n");
      out.write("\n");
      out.write("Connaught Place - Located about 16 kilometres from the hotel, Connaught Place is one of the largest commercial and business centres in New Delhi. While there, you can browse dozens of shops, watch a movie or dine at great restaurants.\n");
      out.write("\n");
      out.write("Humayun's Tomb - This 16th-century mausoleum is less than 30 minutes from the Country Inn & Suites. Humayun's Tomb boasts impressive marble and red sandstone building materials and is set in a Persian-style garden, making it easy to see why the Taj Mahal was modelled after it.\n");
      out.write("\n");
      out.write("Read more about our hotelâs location.\n");
      out.write("\n");
      out.write("Groups & Meetings\n");
      out.write("From corporate events to wedding receptions, the expansive banquet halls at the Country Inn & Suites, Sahibabad are ideal for all types of gatherings. When you book one of our spaces, you receive access to a dedicated event planner who can assist with everything from floral arrangements to custom catering menus. Additionally, each room is equipped with free high-speed Internet and audiovisual equipment.\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
